name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call: {}

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  ZIG_VERSION: "0.16.0"

jobs:
  ci-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Install Zig ${{ env.ZIG_VERSION }}
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      # Cargo nextest has prebuilds for linux, but not for macos or windows.
      # fall-back to `cargo test` instead.
      - name: Install cargo-nextest
        if: matrix.os == 'ubuntu-latest'
        run: cargo binstall --no-confirm cargo-nextest --locked

      - name: Cache cargo registry & target
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}

      - name: Run CI checks
        shell: bash
        run: ./scripts/ci-check
